PerfectTurkey/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PerfectTurkey.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PerfectTurkey/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Web.Mvc;


namespace PerfectTurkey.Pages
{ 
    public class IndexModel : PageModel
    {

        private readonly ILogger<IndexModel> _logger;

        public IndexModel(MakeATurkey makeATurkey, ILogger<IndexModel> logger)
        {
            turkey = makeATurkey;
            _logger = logger;
        }

        public void OnGet()
        {
          

        }
        //create a new instance of the Make a turkey class with the Recipe method. 
        readonly MakeATurkey turkey;
        //set empty string for submission result to be displayed under the submission button
        public string SubmissionResult { get; private set; } = "";
        //taken from Your new favorite poem. https://github.com/MetzinAround/Your-New-Favorite-Poem
        public void OnPostSubmit(string weight)
        {
            //I wasn't sure how to use this from you're new favorite poem without the task/async, so I created a fake await with a delay of 1 second so I could use it. 

            if (weight is null || !double.TryParse(weight, out double doubleWeight))
            {
                SubmissionResult = "Please enter a number";
            }
            else
            {   // realized I could just use the out double from the Try Parse and didn't have to convert the weight to a double here, I had already done it. 
                //var weighted = Convert.ToDouble(weight);

                try
                {
                    SubmissionResult = turkey.Recipe(doubleWeight);
                }
                catch
                {
                    SubmissionResult = "TURKEY, WHAT ARE YOU DOING?";
                }
            }
        }
    }
}

PerfectTurkey/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PerfectTurkey.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PerfectTurkey/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Let's Cook that Turkey</h1>
</div>

<body>
    <div class="turkeyVideo">
        <center><iframe width="733" height="538" src="https://www.youtube.com/embed/Dyxr--0hHWU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>
    </div>

    <br/>

    <form method="post" asp-page="Index">
        <section class="weight">
            <center><input type="text" name="weight" placeholder="How many pounds is the turkey?" size="100"></center>
        </section>
        <br/>
        <section class="submission">
            <center><input class="submissionbutton" type="submit" value="🦃" asp-page-handler="Submit" ></center>
        </section>
    </form>

    <br/>

    <section class="recipe">

        <!-- This solution came from https://stackoverflow.com/a/7602751/13741035 -->

        <center><h2 style="white-space: pre-line">@Model.SubmissionResult</h2></center>
    </section>
</body>

PerfectTurkey/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PerfectTurkey</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>